//! Synthetic traffic, and the patterns a rehearsal replays.
//!
//! `docs/interface.md` §8. Two commands: `synth-trace` writes traffic nobody
//! recorded from anybody, and `import` reduces a trace to the shape of the
//! traffic without carrying any of its content forward.
//!
//! # Sanitised by construction, not by filtering
//!
//! A filter is a list of things somebody thought of. This module never copies
//! a header value at all -- not `Authorization`, not `Cookie`, not the ones
//! nobody has invented yet -- and never copies a body: a body becomes one word
//! saying what shape it had. A token, an address, a card number or a sentence
//! telling a reader what to do cannot survive a transformation that keeps
//! nothing but a type name, and that is a stronger statement than any list of
//! patterns could be.
//!
//! # Trace text is data
//!
//! A trace is input from wherever the traffic came from. Nothing in it selects
//! a code path, changes a criterion, or is read as an instruction: the only
//! things taken from an event are its method, the *shape* of its path, its
//! session, its sequence number and its time, and every one of those is
//! bounded and checked before it is used. The acceptance oracle plants a body
//! that asks for the criteria to be changed, and the answer is that the body
//! is not read.

use crate::cli::{Args, Refused};
use crate::json::{obj, s, Json};
use crate::paths;

/// The schema of the first line of a trace.
pub const TRACE_SCHEMA: &str = "catalyst.trace.v1";
/// The schema of every other line.
pub const EVENT_SCHEMA: &str = "catalyst.trace-event.v1";
/// The schema of what `import` derives.
pub const PATTERNS_SCHEMA: &str = "catalyst.patterns.v1";

/// The code a trace that cannot be replayed is refused with.
pub const TRACE_INVALID: &str = "catalyst.rehearsal.trace_invalid";

fn invalid(detail: impl Into<String>) -> Refused {
    Refused::new(
        TRACE_INVALID,
        detail,
        "every event needs a method, a `path` that is a relative path beginning with `/`, \
         a session and a sequence number; write the trace as one JSON object per line",
    )
}

/// One event, reduced to what a rehearsal may know about it.
#[derive(Debug)]
struct Event {
    t_ms: f64,
    session: String,
    seq: f64,
    method: String,
    /// The path with its identifiers replaced by `{id}`.
    template: String,
    body_shape: &'static str,
}

/// `catalyst rehearse synth-trace --out FILE [--sessions N] [--seed S]`.
pub fn synthesise(args: &Args) -> Result<String, Refused> {
    let named = args.required("out", "rehearse synth-trace")?;
    let sessions = number(args, "sessions", 4)?.clamp(1, 4096) as u64;
    let seed = number(args, "seed", 1)? as u64;

    let mut lines = vec![obj(vec![
        ("schema", s(TRACE_SCHEMA)),
        ("synthetic", Json::Bool(true)),
        ("stand_in", Json::Bool(true)),
        (
            "note",
            s(
                "generated by `catalyst rehearse synth-trace`; synthetic traffic for a \
               stand-in service, not recorded from any real system and not describing one",
            ),
        ),
        ("sessions", Json::Num(sessions as f64)),
        ("seed", Json::Num(seed as f64)),
    ])
    .render()];

    let mut random = Random::from(seed);
    for index in 1..=sessions {
        let session = format!("s{index}");
        let start = random.below(400) as f64;
        let order = format!("o{index}");
        let steps: [(&str, String, String); 3] = [
            (
                "POST",
                "/orders".to_owned(),
                format!(
                    "{{\"item\":\"stand-in-item-{}\",\"qty\":{}}}",
                    random.below(9) + 1,
                    random.below(4) + 1
                ),
            ),
            ("GET", format!("/orders/{order}"), String::new()),
            (
                "POST",
                format!("/orders/{order}/pay"),
                "{\"method\":\"stand-in\"}".to_owned(),
            ),
        ];
        let mut at = start;
        for (seq, (method, path, body)) in steps.iter().enumerate() {
            lines.push(
                obj(vec![
                    ("schema", s(EVENT_SCHEMA)),
                    ("t_ms", Json::Num(at)),
                    ("session", s(&session)),
                    ("seq", Json::Num(seq as f64 + 1.0)),
                    ("method", s(method)),
                    ("path", s(path)),
                    (
                        "headers",
                        obj(vec![("Content-Type", s("application/json"))]),
                    ),
                    ("body", s(body)),
                ])
                .render(),
            );
            at += (random.below(60) + 20) as f64;
        }
    }

    let mut text = lines.join("\n");
    text.push('\n');
    let resolved = paths::resolve(named)?;
    write_file(&resolved.full, named, &text)?;
    Ok(obj(vec![
        ("ok", Json::Bool(true)),
        ("out", s(named)),
        ("sessions", Json::Num(sessions as f64)),
        ("events", Json::Num((sessions * 3) as f64)),
        ("synthetic", Json::Bool(true)),
        ("stand_in", Json::Bool(true)),
    ])
    .render())
}

/// `catalyst rehearse import --trace FILE --out FILE`.
pub fn import(args: &Args) -> Result<String, Refused> {
    let trace_named = args.required("trace", "rehearse import")?;
    let out_named = args.required("out", "rehearse import")?;
    let out = paths::resolve(out_named)?;
    // The whole trace is read and checked before a single byte is written, so
    // a refused trace leaves nothing behind.
    let events = read_events(&paths::read_input(trace_named)?)?;
    let patterns = derive(&events);
    write_file(&out.full, out_named, &patterns.render_pretty())?;
    Ok(obj(vec![
        ("ok", Json::Bool(true)),
        ("out", s(out_named)),
        ("requests", Json::Num(events.len() as f64)),
        ("sanitised", Json::Bool(true)),
    ])
    .render())
}

/// Read every event of a trace, refusing the whole trace if any one of them
/// cannot be replayed.
fn read_events(text: &str) -> Result<Vec<Event>, Refused> {
    let mut events = Vec::new();
    for (number, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let document = Json::parse(line).map_err(|error| {
            invalid(format!(
                "line {} is not one JSON object (at byte {}, expected {})",
                number + 1,
                error.at,
                error.what
            ))
        })?;
        match document.get("schema").and_then(Json::as_str) {
            Some(TRACE_SCHEMA) => continue,
            Some(EVENT_SCHEMA) => {}
            _ => {
                return Err(invalid(format!(
                    "line {} declares no `schema` of \"{TRACE_SCHEMA}\" or \"{EVENT_SCHEMA}\"",
                    number + 1
                )))
            }
        }
        let Some(path) = document.get("path").and_then(Json::as_str) else {
            return Err(invalid(format!(
                "event on line {} has no `path`",
                number + 1
            )));
        };
        if !path.starts_with('/') || path.contains("://") || path.contains("..") {
            return Err(invalid(format!(
                "the path on line {} is not a relative path beginning with `/`; a rehearsal \
                 replays paths on the local stand-in and never a whole address somewhere else",
                number + 1
            )));
        }
        let Some(method) = document.get("method").and_then(Json::as_str) else {
            return Err(invalid(format!(
                "event on line {} has no `method`",
                number + 1
            )));
        };
        let method = word(method, 16);
        if method.is_empty() {
            return Err(invalid(format!(
                "the method on line {} is not a word",
                number + 1
            )));
        }
        events.push(Event {
            t_ms: document
                .get("t_ms")
                .and_then(Json::as_f64)
                .filter(|t| t.is_finite() && *t >= 0.0)
                .unwrap_or(0.0),
            session: {
                let session = word(
                    document.get("session").and_then(Json::as_str).unwrap_or(""),
                    32,
                );
                if session.is_empty() {
                    "s0".to_owned()
                } else {
                    session
                }
            },
            seq: document
                .get("seq")
                .and_then(Json::as_f64)
                .filter(|n| n.is_finite())
                .unwrap_or((events.len() + 1) as f64),
            method: method.to_ascii_uppercase(),
            template: template(path),
            body_shape: shape(document.get("body")),
        });
    }
    Ok(events)
}

/// The shape of the traffic: what was called, how often, how fast it arrived,
/// how much of it overlapped, and in what order. No content of any kind.
fn derive(events: &[Event]) -> Json {
    let mut patterns: Vec<(String, String, usize, &'static str)> = Vec::new();
    for event in events {
        match patterns
            .iter_mut()
            .find(|(m, p, _, _)| *m == event.method && *p == event.template)
        {
            Some(entry) => entry.2 += 1,
            None => patterns.push((
                event.method.clone(),
                event.template.clone(),
                1,
                event.body_shape,
            )),
        }
    }

    let mut times: Vec<f64> = events.iter().map(|event| event.t_ms).collect();
    times.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    let gaps: Vec<f64> = times.windows(2).map(|pair| pair[1] - pair[0]).collect();

    // Sessions in the order they first appear, with the span each one covers.
    let mut spans: Vec<Span> = Vec::new();
    for event in events {
        let step = (event.seq, format!("{} {}", event.method, event.template));
        match spans.iter_mut().find(|span| span.session == event.session) {
            Some(span) => {
                span.first = span.first.min(event.t_ms);
                span.last = span.last.max(event.t_ms);
                span.steps.push(step);
            }
            None => spans.push(Span {
                session: event.session.clone(),
                first: event.t_ms,
                last: event.t_ms,
                steps: vec![step],
            }),
        }
    }

    let sequences: Vec<Json> = spans
        .iter()
        .map(|span| {
            let mut ordered = span.steps.clone();
            ordered.sort_by(|a, b| a.0.partial_cmp(&b.0).unwrap_or(std::cmp::Ordering::Equal));
            obj(vec![
                ("session", s(&span.session)),
                (
                    "steps",
                    Json::Arr(ordered.iter().map(|(_, step)| s(step)).collect()),
                ),
            ])
        })
        .collect();

    obj(vec![
        ("schema", s(PATTERNS_SCHEMA)),
        ("requests", Json::Num(events.len() as f64)),
        (
            "patterns",
            Json::Arr(
                patterns
                    .iter()
                    .map(|(method, path, count, body_shape)| {
                        obj(vec![
                            ("method", s(method)),
                            ("path", s(path)),
                            ("count", Json::Num(*count as f64)),
                            ("body_shape", s(body_shape)),
                        ])
                    })
                    .collect(),
            ),
        ),
        (
            "timing",
            obj(vec![(
                "inter_arrival_ms",
                obj(vec![
                    ("min", Json::Num(least(&gaps))),
                    ("median", Json::Num(median(&gaps))),
                    ("max", Json::Num(greatest(&gaps))),
                ]),
            )]),
        ),
        (
            "concurrency",
            obj(vec![(
                "peak_sessions",
                Json::Num(peak_sessions(&spans) as f64),
            )]),
        ),
        ("sequences", Json::Arr(sequences)),
    ])
}

/// One session: when it started, when it stopped, and what it did in between.
struct Span {
    session: String,
    first: f64,
    last: f64,
    /// `(sequence number, "METHOD /template")`, in arrival order.
    steps: Vec<(f64, String)>,
}

/// How many sessions were ever in flight at once: the largest number of
/// `[first, last]` spans that share a moment. Every session's own start is a
/// moment worth asking about, and one of them is always the busiest.
fn peak_sessions(spans: &[Span]) -> usize {
    let mut peak = 0;
    for span in spans {
        let at = span.first;
        let overlapping = spans
            .iter()
            .filter(|other| other.first <= at && at <= other.last)
            .count();
        peak = peak.max(overlapping);
    }
    peak
}

/// The path with every identifier replaced. A segment is an identifier when it
/// carries a digit: `o17`, `42` and `a1b2` are identifiers, `orders` and `pay`
/// are not.
pub fn template(path: &str) -> String {
    let mut out = String::new();
    for segment in path.split('/') {
        if !out.is_empty() || path.starts_with('/') {
            out.push('/');
        }
        if segment.is_empty() {
            out.pop();
            continue;
        }
        if segment.chars().any(|c| c.is_ascii_digit()) {
            out.push_str("{id}");
        } else {
            out.push_str(&word(segment, 48));
        }
    }
    if out.is_empty() {
        out.push('/');
    }
    out
}

/// What a body was, and nothing about what it said.
fn shape(body: Option<&Json>) -> &'static str {
    let text = match body {
        None | Some(Json::Null) => return "none",
        Some(Json::Obj(_)) => return "object",
        Some(Json::Arr(_)) => return "array",
        Some(Json::Num(_)) => return "number",
        Some(Json::Bool(_)) => return "boolean",
        Some(Json::Str(text)) => text,
    };
    if text.trim().is_empty() {
        return "none";
    }
    match Json::parse(text) {
        Ok(Json::Obj(_)) => "object",
        Ok(Json::Arr(_)) => "array",
        Ok(Json::Num(_)) => "number",
        Ok(Json::Bool(_)) => "boolean",
        _ => "string",
    }
}

/// A word from a trace, reduced to characters that can mean nothing anywhere
/// else: letters, digits, `_`, `-` and `.`, bounded in length.
fn word(text: &str, limit: usize) -> String {
    text.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '_' || *c == '-' || *c == '.')
        .take(limit)
        .collect()
}

/// A trace with fewer than two events has no gap between arrivals at all, and
/// zero is the honest answer rather than an infinity nobody can render.
fn least(values: &[f64]) -> f64 {
    match values.split_first() {
        None => 0.0,
        Some((first, rest)) => rest.iter().copied().fold(*first, f64::min),
    }
}

fn greatest(values: &[f64]) -> f64 {
    values.iter().copied().fold(0.0, f64::max)
}

fn median(values: &[f64]) -> f64 {
    if values.is_empty() {
        return 0.0;
    }
    let mut sorted = values.to_vec();
    sorted.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
    sorted[sorted.len() / 2]
}

/// A flag that has to be a whole number, or a refusal that names it.
pub fn number(args: &Args, name: &str, fallback: i64) -> Result<i64, Refused> {
    match args.value(name) {
        None => Ok(fallback),
        Some(text) => text.trim().parse::<i64>().map_err(|_| {
            Refused::usage(format!(
                "--{name} takes a whole number, and `{}` is not one",
                word(text, 32)
            ))
        }),
    }
}

/// Write one file the user named, creating the directories above it.
pub fn write_file(full: &std::path::Path, named: &str, text: &str) -> Result<(), Refused> {
    if let Some(parent) = full.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    std::fs::write(full, text).map_err(|error| {
        Refused::new(
            "catalyst.path_refused",
            format!(
                "`{named}` could not be written: {}",
                format!("{:?}", error.kind()).to_lowercase()
            ),
            "name a file inside the current directory that this user may write",
        )
    })
}

/// A small deterministic generator, so a seed names one trace for ever.
///
/// This is a linear congruential generator with the constants of Numerical
/// Recipes. It is not, and must never be used as, a source of randomness for
/// anything that has to be unguessable; it exists so that two runs of
/// `synth-trace --seed 7` produce the same bytes.
pub struct Random(u64);

impl Random {
    pub fn from(seed: u64) -> Random {
        Random(seed.wrapping_mul(6_364_136_223_846_793_005).wrapping_add(1))
    }

    pub fn below(&mut self, bound: u64) -> u64 {
        self.0 = self.0.wrapping_mul(1_664_525).wrapping_add(1_013_904_223);
        if bound == 0 {
            0
        } else {
            (self.0 >> 17) % bound
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn trace() -> String {
        [
            format!("{{\"schema\":\"{TRACE_SCHEMA}\",\"synthetic\":true}}"),
            format!(
                "{{\"schema\":\"{EVENT_SCHEMA}\",\"t_ms\":0,\"session\":\"s1\",\"seq\":1,\
                     \"method\":\"POST\",\"path\":\"/orders\",\
                     \"headers\":{{\"Authorization\":\"Bearer SECRET-abcdef\"}},\
                     \"body\":\"{{\\\"item\\\":\\\"widget\\\"}}\"}}"
            ),
            format!(
                "{{\"schema\":\"{EVENT_SCHEMA}\",\"t_ms\":40,\"session\":\"s1\",\"seq\":2,\
                     \"method\":\"GET\",\"path\":\"/orders/o1\",\"headers\":{{}},\"body\":\"\"}}"
            ),
            format!(
                "{{\"schema\":\"{EVENT_SCHEMA}\",\"t_ms\":10,\"session\":\"s2\",\"seq\":1,\
                     \"method\":\"POST\",\"path\":\"/orders\",\"headers\":{{}},\
                     \"body\":\"{{\\\"item\\\":\\\"gadget\\\"}}\"}}"
            ),
        ]
        .join("\n")
    }

    #[test]
    fn no_header_value_and_no_body_content_survives_the_import() {
        let events = read_events(&trace()).expect("read");
        let derived = derive(&events).render();
        for secret in ["SECRET", "Bearer", "Authorization", "widget", "gadget"] {
            assert!(!derived.contains(secret), "`{secret}` survived:\n{derived}");
        }
    }

    #[test]
    fn identifiers_in_paths_become_templates_and_sequences_keep_their_order() {
        assert_eq!(template("/orders/o1/pay"), "/orders/{id}/pay");
        assert_eq!(template("/orders"), "/orders");
        assert_eq!(template("/health"), "/health");
        assert_eq!(template("/"), "/");
        let derived = derive(&read_events(&trace()).expect("read"));
        let sequences = derived
            .get("sequences")
            .and_then(Json::as_arr)
            .expect("seq");
        let first = sequences[0]
            .get("steps")
            .and_then(Json::as_arr)
            .expect("steps");
        assert_eq!(first[0].as_str(), Some("POST /orders"));
        assert_eq!(first[1].as_str(), Some("GET /orders/{id}"));
    }

    #[test]
    fn overlapping_sessions_are_counted_and_gaps_are_measured() {
        let derived = derive(&read_events(&trace()).expect("read"));
        assert_eq!(
            derived
                .get("concurrency")
                .and_then(|c| c.get("peak_sessions"))
                .and_then(Json::as_f64),
            Some(2.0)
        );
        assert_eq!(derived.get("requests").and_then(Json::as_f64), Some(3.0));
    }

    #[test]
    fn a_whole_address_in_a_trace_is_refused_and_the_trace_with_it() {
        let bad = format!(
            "{{\"schema\":\"{EVENT_SCHEMA}\",\"t_ms\":0,\"session\":\"s1\",\"seq\":1,\
             \"method\":\"POST\",\"path\":\"https://mail.example.com/send\",\
             \"headers\":{{}},\"body\":\"\"}}"
        );
        assert_eq!(read_events(&bad).expect_err("refused").code, TRACE_INVALID);
    }

    #[test]
    fn one_seed_names_one_trace() {
        let mut a = Random::from(7);
        let mut b = Random::from(7);
        let mut c = Random::from(8);
        let first: Vec<u64> = (0..8).map(|_| a.below(100)).collect();
        let same: Vec<u64> = (0..8).map(|_| b.below(100)).collect();
        let other: Vec<u64> = (0..8).map(|_| c.below(100)).collect();
        assert_eq!(first, same);
        assert_ne!(first, other);
    }
}
