//! The exported `function.go`: the engine's own IR, written out as Go.
//!
//! # Why this is generated from the IR and not from the source text
//!
//! Because the number the Go must reproduce is the number the engine
//! computes, and the engine does not compute the source text. It parses it,
//! runs the optimiser over it, and differentiates the *optimised* form -- that
//! reordering is the whole thesis of the project, and it moves the last bits
//! of every result. A generator that re-read the expression and emitted a
//! textbook derivative would agree to about eight digits and disagree in a way
//! nobody could explain.
//!
//! So this runs exactly what [`crate::api::gradient`] runs -- `text::parse`,
//! `optimise(…, Level::Full)`, `revdiff` -- and then prints the straight-line
//! SSA of the differentiated function, one Go statement per instruction,
//! mirroring [`crate::interp`] operation for operation. The Go and the
//! interpreter execute the same instruction list in the same order, so the
//! only difference left is the platform's own floating point, which is what
//! the declared tolerance is for.
//!
//! # The memory model
//!
//! One `[]float64`, exactly like [`crate::interp::Memory`]: a pointer is an
//! index into it, `Alloca` appends, `Gep` adds, `Load` and `Store` index. The
//! gradient buffer is slots `0..len(InputNames)`, which is where
//! [`crate::api::gradient`] puts it too, so the reverse pass's stores land in
//! the same places.
//!
//! # Dead instructions are dropped
//!
//! Not as an optimisation -- Go refuses to compile a declared variable nobody
//! reads, so an adjoint the sweep produced and never used would be a build
//! error rather than a wasted multiply. A backwards liveness walk keeps every
//! store and everything the returned value depends on, and nothing else.

use crate::cli::Refused;
use crate::ir::{BinOp, Func, IntOp, Op, Pred, Ty, UnOp, Value};
use crate::lower::{self, straight_line};
use crate::problem::Problem;
use std::fmt::Write as _;

/// Emit `function.go` for a validated problem.
pub fn function_go(problem: &Problem) -> Result<String, Refused> {
    // The one instruction list every export renders. `catalyst export r`
    // renders this same list, which is what makes the two agree.
    let lowered = lower::lower(problem)?;
    let arity = lowered.arity;
    let f = lowered.func();

    let body = emit_body(f, arity)?;

    let mut out = String::new();
    out.push_str(
        "// Generated by `catalyst export go` from the problem's optimised IR and its\n\
         // reverse-mode adjoint. Every statement below is one IR instruction.\n\
         //\n\
         // Do not edit: regenerate the export instead.\n\n\
         package main\n\n",
    );
    if body.contains("math.") {
        out.push_str("import \"math\"\n\n");
    }

    let names: Vec<String> = problem.params.iter().map(|p| go_string(p)).collect();
    let _ = writeln!(out, "var InputNames = []string{{{}}}", names.join(", "));
    let mins: Vec<String> = problem.domains.iter().map(|d| literal(d.min)).collect();
    let maxs: Vec<String> = problem.domains.iter().map(|d| literal(d.max)).collect();
    let _ = writeln!(out, "\nvar InputMin = []float64{{{}}}", mins.join(", "));
    let _ = writeln!(out, "var InputMax = []float64{{{}}}", maxs.join(", "));

    out.push_str(
        "\n// InDomain reports whether every input lies inside its declared range,\n\
         // and names the first one that does not.\n\
         func InDomain(in []float64) (bool, string) {\n\
         \tif len(in) != len(InputNames) {\n\
         \t\treturn false, \"the wrong number of inputs was given\"\n\
         \t}\n\
         \tfor i, name := range InputNames {\n\
         \t\tif in[i] < InputMin[i] {\n\
         \t\t\treturn false, name + \" is below its declared minimum\"\n\
         \t\t}\n\
         \t\tif in[i] > InputMax[i] {\n\
         \t\t\treturn false, name + \" is above its declared maximum\"\n\
         \t\t}\n\
         \t}\n\
         \treturn true, \"\"\n\
         }\n\n\
         // Value is the function's value alone. It runs the same code Gradient does,\n\
         // so the two can never disagree about the value.\n\
         func Value(in []float64) float64 {\n\
         \tvalue, _ := Gradient(in)\n\
         \treturn value\n\
         }\n\n\
         // Gradient returns the value and one partial derivative per input, in\n\
         // InputNames order.\n\
         func Gradient(in []float64) (float64, []float64) {\n\
         \tmem := make([]float64, len(InputNames))\n\
         \t_ = mem\n",
    );
    out.push_str(&body);
    out.push_str("}\n");
    out.push_str(&helpers(&body));
    Ok(out)
}

/// The straight-line body, and the `return` that ends it.
fn emit_body(f: &Func, arity: usize) -> Result<String, Refused> {
    let (keep, returned) = straight_line(f)?;
    let mut body = String::new();
    for v in keep {
        emit_inst(f, v, arity, &mut body)?;
    }
    match returned {
        Some(r) => {
            let _ = writeln!(body, "\treturn {}, mem[:len(InputNames)]", reg(r));
        }
        None => body.push_str("\treturn 0, mem[:len(InputNames)]\n"),
    }
    Ok(body)
}

fn emit_inst(f: &Func, v: Value, arity: usize, out: &mut String) -> Result<(), Refused> {
    let a = |x: &Value| reg(*x);
    let name = reg(v);
    let real = |out: &mut String, expr: String| {
        let _ = writeln!(out, "\tvar {name} float64 = {expr}");
    };
    let int = |out: &mut String, expr: String| {
        let _ = writeln!(out, "\tvar {name} int64 = {expr}");
    };
    match f.op(v) {
        Op::ConstReal(c) => real(out, literal(*c)),
        Op::ConstInt(c) => int(out, format!("{c}")),
        Op::Param(index) => {
            let index = *index as usize;
            if index < arity {
                real(out, format!("in[{index}]"));
            } else if index == arity {
                // The gradient buffer, which lives at slot zero.
                int(out, "0".to_owned());
            } else if index == arity + 1 {
                // The seed: the adjoint of the returned value.
                real(out, "1.0".to_owned());
            } else {
                return Err(unsupported("a parameter the export does not know"));
            }
        }
        Op::Un(o, x) => real(out, unary(*o, &a(x))),
        Op::Bin(o, x, y) => real(out, binary(*o, &a(x), &a(y))),
        Op::Int(o, x, y) => int(out, integer(*o, &a(x), &a(y))),
        Op::FCmp(p, x, y) => int(out, format!("catBool({} {} {})", a(x), compare(*p), a(y))),
        Op::ICmp(p, x, y) => int(out, integer_compare(*p, &a(x), &a(y))),
        Op::Select(c, x, y) => {
            let ty = go_type(f.ty(v))?;
            let _ = writeln!(out, "\tvar {name} {ty}");
            let _ = writeln!(out, "\tif {} != 0 {{", a(c));
            let _ = writeln!(out, "\t\t{name} = {}", a(x));
            let _ = writeln!(out, "\t}} else {{");
            let _ = writeln!(out, "\t\t{name} = {}", a(y));
            let _ = writeln!(out, "\t}}");
        }
        Op::Alloca(n) => int(out, format!("catAlloc(&mem, {})", a(n))),
        Op::Gep(p, offset) => int(out, format!("{} + {}", a(p), a(offset))),
        Op::Load(p) => real(out, format!("mem[{}]", a(p))),
        Op::Store(p, x) => {
            let _ = writeln!(out, "\tmem[{}] = {}", a(p), a(x));
        }
        Op::IntToReal(x) => real(out, format!("float64({})", a(x))),
        Op::RealToInt(x) => int(out, format!("int64({})", a(x))),
        Op::Phi(_) => return Err(unsupported("a phi node, which needs control flow")),
        Op::Call(_, _) => return Err(unsupported("a call into another function")),
    }
    Ok(())
}

fn unary(o: UnOp, x: &str) -> String {
    match o {
        UnOp::Neg => format!("-{x}"),
        UnOp::Sin => format!("math.Sin({x})"),
        UnOp::Cos => format!("math.Cos({x})"),
        UnOp::Tan => format!("math.Tan({x})"),
        UnOp::Exp => format!("math.Exp({x})"),
        UnOp::Log => format!("math.Log({x})"),
        UnOp::Sqrt => format!("math.Sqrt({x})"),
        UnOp::Tanh => format!("math.Tanh({x})"),
        UnOp::Sinh => format!("math.Sinh({x})"),
        UnOp::Cosh => format!("math.Cosh({x})"),
        UnOp::Abs => format!("math.Abs({x})"),
        UnOp::Recip => format!("1.0 / {x}"),
        UnOp::Erf => format!("math.Erf({x})"),
    }
}

fn binary(o: BinOp, x: &str, y: &str) -> String {
    match o {
        BinOp::Add => format!("{x} + {y}"),
        BinOp::Sub => format!("{x} - {y}"),
        BinOp::Mul => format!("{x} * {y}"),
        BinOp::Div => format!("{x} / {y}"),
        BinOp::Pow => format!("math.Pow({x}, {y})"),
        // Not math.Max: that one has its own rules about NaN and signed zero,
        // and the engine's rule is `a >= b ? a : b`. The helper is that rule.
        BinOp::Max => format!("catMax({x}, {y})"),
        BinOp::Min => format!("catMin({x}, {y})"),
        BinOp::Atan2 => format!("math.Atan2({x}, {y})"),
    }
}

fn integer(o: IntOp, x: &str, y: &str) -> String {
    match o {
        IntOp::Add => format!("{x} + {y}"),
        IntOp::Sub => format!("{x} - {y}"),
        IntOp::Mul => format!("{x} * {y}"),
        // The engine's integer division yields zero rather than trapping.
        IntOp::Div => format!("catIdiv({x}, {y})"),
        IntOp::Rem => format!("catIrem({x}, {y})"),
        // The unsigned pair works on the same bits read as uint64, which is
        // exactly what the engine does.
        IntOp::UDiv => format!("catUdiv({x}, {y})"),
        IntOp::URem => format!("catUrem({x}, {y})"),
        IntOp::And => format!("{x} & {y}"),
        IntOp::Or => format!("{x} | {y}"),
        IntOp::Xor => format!("{x} ^ {y}"),
        IntOp::Shl => format!("{x} << uint64({y}&63)"),
        IntOp::Shr => format!("{x} >> uint64({y}&63)"),
        IntOp::LShr => format!("int64(uint64({x}) >> uint64({y}&63))"),
    }
}

fn compare(p: Pred) -> &'static str {
    match p {
        Pred::Lt | Pred::ULt => "<",
        Pred::Le | Pred::ULe => "<=",
        Pred::Gt | Pred::UGt => ">",
        Pred::Ge | Pred::UGe => ">=",
        Pred::Eq => "==",
        Pred::Ne => "!=",
    }
}

/// An integer comparison in Go: the six signed orderings compare the int64s,
/// the four unsigned ones compare the same bits as uint64.
fn integer_compare(p: Pred, x: &str, y: &str) -> String {
    if p.unsigned() {
        format!("catBool(uint64({x}) {} uint64({y}))", compare(p))
    } else {
        format!("catBool({x} {} {y})", compare(p))
    }
}

fn go_type(ty: Ty) -> Result<&'static str, Refused> {
    match ty {
        Ty::Real => Ok("float64"),
        Ty::Int | Ty::Ptr => Ok("int64"),
        Ty::Void => Err(unsupported("a select yielding nothing")),
    }
}

/// Only the helpers the body actually calls, so the export carries no code
/// that is never reached.
fn helpers(body: &str) -> String {
    let mut out = String::new();
    if body.contains("catBool(") {
        out.push_str(
            "\n// catBool is the engine's comparison result: one for true, zero for false.\n\
             func catBool(b bool) int64 {\n\
             \tif b {\n\
             \t\treturn 1\n\
             \t}\n\
             \treturn 0\n\
             }\n",
        );
    }
    if body.contains("catMax(") {
        out.push_str(
            "\n// catMax is the engine's max: the first operand when it is not smaller.\n\
             func catMax(a, b float64) float64 {\n\
             \tif a >= b {\n\
             \t\treturn a\n\
             \t}\n\
             \treturn b\n\
             }\n",
        );
    }
    if body.contains("catMin(") {
        out.push_str(
            "\n// catMin is the engine's min: the first operand when it is not larger.\n\
             func catMin(a, b float64) float64 {\n\
             \tif a <= b {\n\
             \t\treturn a\n\
             \t}\n\
             \treturn b\n\
             }\n",
        );
    }
    if body.contains("catIdiv(") {
        out.push_str(
            "\nfunc catIdiv(a, b int64) int64 {\n\
             \tif b == 0 {\n\
             \t\treturn 0\n\
             \t}\n\
             \treturn a / b\n\
             }\n",
        );
    }
    if body.contains("catIrem(") {
        out.push_str(
            "\nfunc catIrem(a, b int64) int64 {\n\
             \tif b == 0 {\n\
             \t\treturn 0\n\
             \t}\n\
             \treturn a % b\n\
             }\n",
        );
    }
    if body.contains("catUdiv(") {
        out.push_str(
            "\nfunc catUdiv(a, b int64) int64 {\n\
             \tif b == 0 {\n\
             \t\treturn 0\n\
             \t}\n\
             \treturn int64(uint64(a) / uint64(b))\n\
             }\n",
        );
    }
    if body.contains("catUrem(") {
        out.push_str(
            "\nfunc catUrem(a, b int64) int64 {\n\
             \tif b == 0 {\n\
             \t\treturn 0\n\
             \t}\n\
             \treturn int64(uint64(a) % uint64(b))\n\
             }\n",
        );
    }
    if body.contains("catAlloc(") {
        out.push_str(
            "\n// catAlloc reserves slots the way the engine's linear memory does: it\n\
             // bumps the high-water mark, never frees, and starts every slot at zero.\n\
             func catAlloc(mem *[]float64, n int64) int64 {\n\
             \tif n < 1 {\n\
             \t\tn = 1\n\
             \t}\n\
             \tat := int64(len(*mem))\n\
             \t*mem = append(*mem, make([]float64, n)...)\n\
             \treturn at\n\
             }\n",
        );
    }
    out
}

fn reg(v: Value) -> String {
    format!("v{v}")
}

/// A `f64` as a Go literal. The shortest form that reads back as the same
/// double, which is what Rust's own debug formatting produces, so the two
/// languages start from bit-identical constants.
pub fn literal(x: f64) -> String {
    if x.is_nan() {
        return "math.NaN()".to_owned();
    }
    if x.is_infinite() {
        return if x > 0.0 {
            "math.Inf(1)".to_owned()
        } else {
            "math.Inf(-1)".to_owned()
        };
    }
    format!("{x:?}")
}

/// A Go string literal. Go's interpreted strings take the same escapes JSON
/// does for everything that appears in a parameter name.
pub fn go_string(text: &str) -> String {
    crate::json::s(text).render()
}

fn unsupported(what: &str) -> Refused {
    lower::unsupported(what)
}
