//! The exported `function.R`: the engine's own IR, written out as base R.
//!
//! `docs/interface.md` §9. This is [`crate::gocode`]'s sibling, and the
//! resemblance is the point: both render the one instruction list
//! [`crate::lower`] produces, statement for statement, in the same order. The
//! R and the Go are two spellings of one computation rather than two
//! implementations that agree today.
//!
//! # Base R, and nothing else
//!
//! No package is loaded, by any spelling. Somebody handed this directory can
//! run it with the R they already have, on a machine with no network and no
//! library path they are allowed to write to -- which is the same promise the
//! Go export makes with a `go.mod` that has no `require`.
//!
//! # Where R differs from Go, and what is done about it
//!
//! * **Vectors are one-based.** The engine's pointers are zero-based offsets
//!   into one flat memory, exactly as in [`crate::interp`], so every access
//!   below is written `mem[p + 1]`. The arithmetic on pointers stays
//!   zero-based; only the indexing step adjusts.
//! * **There is no integer type worth using here.** R's integers are 32-bit
//!   and overflow to `NA`; doubles hold every index this IR can produce
//!   exactly, so integer-typed registers are doubles with integer semantics,
//!   and division truncates through [`R_HELPERS`] rather than by R's rules.
//! * **`mem` cannot be grown through a helper.** R passes by value, so an
//!   allocation is emitted inline -- read the length, then extend -- instead
//!   of calling something that would grow a copy nobody sees.

use crate::cli::Refused;
use crate::ir::{BinOp, Func, IntOp, Op, Pred, UnOp, Value};
use crate::lower::{self, straight_line};
use crate::problem::Problem;
use std::fmt::Write as _;

/// Emit `function.R` for a validated problem.
pub fn function_r(problem: &Problem) -> Result<String, Refused> {
    let lowered = lower::lower(problem)?;
    let arity = lowered.arity;
    let f = lowered.func();
    let body = emit_body(f, arity)?;

    let mut out = String::new();
    out.push_str(
        "# Generated by `catalyst export r` from the problem's optimised IR and its\n\
         # reverse-mode adjoint. Every statement below is one IR instruction, and it is\n\
         # the same instruction list the Go export renders.\n\
         #\n\
         # Base R only: no package is loaded. Do not edit; regenerate the export.\n\n",
    );

    let names: Vec<String> = problem.params.iter().map(|p| r_string(p)).collect();
    let _ = writeln!(out, "catalyst_input_names <- c({})", names.join(", "));
    let mins: Vec<String> = problem.domains.iter().map(|d| literal(d.min)).collect();
    let maxs: Vec<String> = problem.domains.iter().map(|d| literal(d.max)).collect();
    let _ = writeln!(out, "catalyst_input_min <- c({})", mins.join(", "));
    let _ = writeln!(out, "catalyst_input_max <- c({})", maxs.join(", "));

    out.push_str(&R_HELPERS_HEADER.replace("{{HELPERS}}", &helpers(&body)));
    out.push_str(&body);
    out.push_str(R_WRAPPERS);
    Ok(out)
}

/// The straight-line body of `catalyst_run`, and the list it returns.
fn emit_body(f: &Func, arity: usize) -> Result<String, Refused> {
    let (keep, returned) = straight_line(f)?;
    let mut body = String::new();
    for v in keep {
        emit_inst(f, v, arity, &mut body)?;
    }
    match returned {
        Some(r) => {
            let _ = writeln!(
                body,
                "  list(value = {}, gradient = mem[seq_along(catalyst_input_names)])",
                reg(r)
            );
        }
        None => {
            body.push_str("  list(value = 0, gradient = mem[seq_along(catalyst_input_names)])\n")
        }
    }
    body.push_str("}\n");
    Ok(body)
}

fn emit_inst(f: &Func, v: Value, arity: usize, out: &mut String) -> Result<(), Refused> {
    let a = |x: &Value| reg(*x);
    let name = reg(v);
    let set = |out: &mut String, expr: String| {
        let _ = writeln!(out, "  {name} <- {expr}");
    };
    match f.op(v) {
        Op::ConstReal(c) => set(out, literal(*c)),
        Op::ConstInt(c) => set(out, format!("{c}")),
        Op::Param(index) => {
            let index = *index as usize;
            if index < arity {
                set(out, format!("inputs[[{}]]", index + 1));
            } else if index == arity {
                // The gradient buffer, which lives at offset zero.
                set(out, "0".to_owned());
            } else if index == arity + 1 {
                // The seed: the adjoint of the returned value.
                set(out, "1".to_owned());
            } else {
                return Err(lower::unsupported("a parameter the export does not know"));
            }
        }
        Op::Un(o, x) => set(out, unary(*o, &a(x))?),
        Op::Bin(o, x, y) => set(out, binary(*o, &a(x), &a(y))),
        Op::Int(o, x, y) => set(out, integer(*o, &a(x), &a(y))),
        Op::FCmp(p, x, y) | Op::ICmp(p, x, y) => set(
            out,
            format!("catalyst_bool({} {} {})", a(x), compare(*p), a(y)),
        ),
        Op::Select(c, x, y) => set(out, format!("if ({} != 0) {} else {}", a(c), a(x), a(y))),
        Op::Alloca(n) => {
            // Inline, because R would grow a copy the caller never sees.
            let _ = writeln!(out, "  {name} <- length(mem)");
            let _ = writeln!(out, "  mem <- c(mem, rep(0, max(1, {})))", a(n));
        }
        Op::Gep(p, offset) => set(out, format!("{} + {}", a(p), a(offset))),
        Op::Load(p) => set(out, format!("mem[[{} + 1]]", a(p))),
        Op::Store(p, x) => {
            let _ = writeln!(out, "  mem[[{} + 1]] <- {}", a(p), a(x));
        }
        Op::IntToReal(x) | Op::RealToInt(x) => set(out, a(x)),
        Op::Phi(_) => return Err(lower::unsupported("a phi node, which needs control flow")),
        Op::Call(_, _) => return Err(lower::unsupported("a call into another function")),
    }
    Ok(())
}

fn unary(o: UnOp, x: &str) -> Result<String, Refused> {
    Ok(match o {
        UnOp::Neg => format!("-{x}"),
        UnOp::Sin => format!("sin({x})"),
        UnOp::Cos => format!("cos({x})"),
        UnOp::Tan => format!("tan({x})"),
        UnOp::Exp => format!("exp({x})"),
        UnOp::Log => format!("log({x})"),
        UnOp::Sqrt => format!("sqrt({x})"),
        UnOp::Tanh => format!("tanh({x})"),
        UnOp::Sinh => format!("sinh({x})"),
        UnOp::Cosh => format!("cosh({x})"),
        UnOp::Abs => format!("abs({x})"),
        UnOp::Recip => format!("1 / {x}"),
        // Base R has no `erf`, but it has `pnorm`, and the relation between
        // them is an identity rather than an approximation:
        //
        //     erf(x) = 2 * pnorm(x * sqrt(2)) - 1
        //
        // `pnorm` needs no package loaded and no `::`, so the export stays
        // self-contained. Measured against the engine at x = 0.1, 0.5, 1.0,
        // 2.0 and 3.5, the largest relative disagreement is about 4e-16 --
        // six orders of magnitude inside the 1e-9 the fixtures declare. The
        // derivative needs nothing special at all: the adjoint sweep emits
        // `2 / sqrt(pi) * exp(0 - x * x)` as ordinary instructions, which
        // this printer already renders.
        UnOp::Erf => format!("catalyst_erf({x})"),
    })
}

fn binary(o: BinOp, x: &str, y: &str) -> String {
    match o {
        BinOp::Add => format!("{x} + {y}"),
        BinOp::Sub => format!("{x} - {y}"),
        BinOp::Mul => format!("{x} * {y}"),
        BinOp::Div => format!("{x} / {y}"),
        BinOp::Pow => format!("{x} ^ {y}"),
        // Not R's `max`: that one propagates NA differently and takes any
        // number of arguments. The engine's rule is `a >= b ? a : b`.
        BinOp::Max => format!("catalyst_max({x}, {y})"),
        BinOp::Min => format!("catalyst_min({x}, {y})"),
        BinOp::Atan2 => format!("atan2({x}, {y})"),
    }
}

fn integer(o: IntOp, x: &str, y: &str) -> String {
    match o {
        IntOp::Add => format!("{x} + {y}"),
        IntOp::Sub => format!("{x} - {y}"),
        IntOp::Mul => format!("{x} * {y}"),
        // The engine's integer division yields zero rather than trapping, and
        // truncates towards zero rather than towards minus infinity.
        IntOp::Div => format!("catalyst_idiv({x}, {y})"),
        IntOp::Rem => format!("catalyst_irem({x}, {y})"),
        // R carries these integers as doubles, so the unsigned pair is the
        // signed pair on a value that is never negative in the code this
        // printer sees: the expression language has no integer arithmetic at
        // all, and every counter the transforms introduce starts at zero and
        // grows.
        IntOp::UDiv => format!("catalyst_idiv({x}, {y})"),
        IntOp::URem => format!("catalyst_irem({x}, {y})"),
        IntOp::And => format!("bitwAnd({x}, {y})"),
        IntOp::Or => format!("bitwOr({x}, {y})"),
        IntOp::Xor => format!("bitwXor({x}, {y})"),
        IntOp::Shl => format!("bitwShiftL({x}, bitwAnd({y}, 63))"),
        IntOp::Shr => format!("bitwShiftR({x}, bitwAnd({y}, 63))"),
        IntOp::LShr => format!("bitwShiftR({x}, bitwAnd({y}, 63))"),
    }
}

fn compare(p: Pred) -> &'static str {
    match p {
        Pred::Lt | Pred::ULt => "<",
        Pred::Le | Pred::ULe => "<=",
        Pred::Gt | Pred::UGt => ">",
        Pred::Ge | Pred::UGe => ">=",
        Pred::Eq => "==",
        Pred::Ne => "!=",
    }
}

/// Only the helpers the body actually calls.
fn helpers(body: &str) -> String {
    let mut out = String::new();
    if body.contains("catalyst_bool(") {
        out.push_str("catalyst_bool <- function(b) if (isTRUE(b)) 1 else 0\n\n");
    }
    if body.contains("catalyst_max(") {
        out.push_str("catalyst_max <- function(a, b) if (a >= b) a else b\n\n");
    }
    if body.contains("catalyst_min(") {
        out.push_str("catalyst_min <- function(a, b) if (a <= b) a else b\n\n");
    }
    if body.contains("catalyst_idiv(") {
        out.push_str("catalyst_idiv <- function(a, b) if (b == 0) 0 else trunc(a / b)\n\n");
    }
    if body.contains("catalyst_irem(") {
        out.push_str("catalyst_irem <- function(a, b) if (b == 0) 0 else a - b * trunc(a / b)\n\n");
    }
    if body.contains("catalyst_erf(") {
        out.push_str(
            "# erf(x) = 2 * pnorm(x * sqrt(2)) - 1 is an identity, not an approximation:\n\
             # pnorm is the normal distribution function base R already carries, and the\n\
             # two differ by about 4e-16 relative at worst, far inside the tolerance the\n\
             # fixtures declare. No package is loaded to get it.\n\
             catalyst_erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1\n\n",
        );
    }
    out
}

/// What comes between the declarations and the emitted body: the helpers the
/// body needs, the domain check, and the head of `catalyst_run`.
const R_HELPERS_HEADER: &str = r#"
# The declared range of every parameter, checked before anything is computed.
catalyst_in_domain <- function(p) {
  for (i in seq_along(catalyst_input_names)) {
    name <- catalyst_input_names[[i]]
    if (is.null(p[[name]])) {
      return(list(ok = FALSE, why = paste0(name, " was not given a value")))
    }
    if (p[[name]] < catalyst_input_min[[i]]) {
      return(list(ok = FALSE, why = paste0(name, " is below its declared minimum")))
    }
    if (p[[name]] > catalyst_input_max[[i]]) {
      return(list(ok = FALSE, why = paste0(name, " is above its declared maximum")))
    }
  }
  list(ok = TRUE, why = "")
}

{{HELPERS}}# catalyst_run is the whole computation: one statement per IR instruction,
# in the order the engine executes them. It returns the value and the
# gradient together, because they are produced by one pass and must never be
# able to disagree.
catalyst_run <- function(p) {
  inputs <- vapply(catalyst_input_names, function(name) as.numeric(p[[name]]), numeric(1))
  mem <- rep(0, length(catalyst_input_names))
"#;

/// The two functions §9 names, on top of `catalyst_run`.
const R_WRAPPERS: &str = r#"
# The value at p, where p is a named list of parameter values.
catalyst_value <- function(p) catalyst_run(p)$value

# The gradient at p, as a named list with one partial derivative per
# parameter, in declaration order.
catalyst_gradient <- function(p) {
  gradient <- catalyst_run(p)$gradient
  out <- as.list(gradient)
  names(out) <- catalyst_input_names
  out
}
"#;

fn reg(v: Value) -> String {
    format!("v{v}")
}

/// A `f64` as an R literal.
///
/// R reads a decimal literal with `strtod`, exactly as Rust writes one, so the
/// shortest form that round-trips in Rust round-trips in R too and the two
/// languages start from bit-identical constants. `Display` rather than
/// `Debug`, because `Debug` writes `1e-12` where `Display` writes the digits
/// out, and the fixtures are compared as text against `Display`.
pub fn literal(x: f64) -> String {
    if x.is_nan() {
        return "NaN".to_owned();
    }
    if x.is_infinite() {
        return if x > 0.0 { "Inf" } else { "-Inf" }.to_owned();
    }
    format!("{x}")
}

/// An R string literal. R's double-quoted strings take the same escapes JSON
/// does for everything that can appear in a parameter name.
pub fn r_string(text: &str) -> String {
    crate::json::s(text).render()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn problem(function: &str, name: &str) -> Problem {
        crate::problem::parse(&format!(
            "{{\"schema\":\"catalyst.problem.v1\",\"name\":\"p\",\"goal\":\"g\",\
             \"function\":{},\"inputs\":{{\"{name}\":2}},\
             \"domains\":{{\"{name}\":{{\"min\":0,\"max\":9,\"unit\":\"\"}}}}}}",
            crate::json::s(function).render()
        ))
        .expect("valid")
    }

    #[test]
    fn the_generated_r_loads_no_package_by_any_spelling() {
        let text = function_r(&problem("func p(x) = x * x + sin(x)", "x")).expect("emitted");
        for forbidden in ["library(", "require(", "requireNamespace(", "::"] {
            assert!(!text.contains(forbidden), "`{forbidden}` in:\n{text}");
        }
    }

    #[test]
    fn it_declares_the_two_functions_the_interface_names() {
        let text = function_r(&problem("func p(x) = x * x", "x")).expect("emitted");
        assert!(text.contains("catalyst_value <- function(p)"));
        assert!(text.contains("catalyst_gradient <- function(p)"));
        assert!(text.contains("catalyst_in_domain <- function(p)"));
    }

    /// A literal has to read back as the same double in R, and has to be
    /// written the way the fixtures are compared: `Display`, not `Debug`.
    #[test]
    fn literals_are_written_the_way_the_fixtures_are_compared() {
        assert_eq!(literal(12.0), "12");
        assert_eq!(literal(1.5), "1.5");
        assert_eq!(literal(1e-12), format!("{}", 1e-12));
        assert!(!literal(1e-12).contains('e'), "{}", literal(1e-12));
        assert_eq!(literal(f64::NAN), "NaN");
        assert_eq!(literal(f64::INFINITY), "Inf");
        assert_eq!(literal(f64::NEG_INFINITY), "-Inf");
    }

    /// Only the helpers the body reaches, so nothing unreachable ships.
    #[test]
    fn a_helper_no_statement_calls_is_not_emitted() {
        let text = function_r(&problem("func p(x) = x + 1", "x")).expect("emitted");
        assert!(!text.contains("catalyst_idiv"));
        assert!(!text.contains("catalyst_max"));
    }

    /// `erf` reaches R through an identity, not an approximation, and
    /// without loading anything.
    #[test]
    fn erf_is_emitted_through_pnorm_and_agrees_with_the_engine() {
        let text = function_r(&problem("func p(x) = erf(x)", "x")).expect("emitted");
        assert!(text.contains("catalyst_erf <- function(x) 2 * pnorm(x * sqrt(2)) - 1"));
        for forbidden in ["library(", "require(", "requireNamespace(", "::"] {
            assert!(!text.contains(forbidden), "`{forbidden}` in:\n{text}");
        }
        // The adjoint of erf is ordinary arithmetic the printer already
        // renders, so the gradient needs no helper of its own.
        assert!(text.contains("exp("), "{text}");
    }

    /// Every unary the engine has is renderable: a refusal here would shut a
    /// class of problems out of R, and none is left.
    #[test]
    fn no_unary_operation_is_refused_by_the_r_backend() {
        for (name, at) in [
            ("neg", "0 - x"),
            ("sin", "sin(x)"),
            ("cos", "cos(x)"),
            ("tan", "tan(x)"),
            ("exp", "exp(x)"),
            ("log", "log(x)"),
            ("sqrt", "sqrt(x)"),
            ("tanh", "tanh(x)"),
            ("sinh", "sinh(x)"),
            ("cosh", "cosh(x)"),
            ("abs", "abs(x)"),
            ("erf", "erf(x)"),
        ] {
            let source = format!("func p(x) = {at}");
            function_r(&problem(&source, "x"))
                .unwrap_or_else(|refused| panic!("{name}: {}", refused.detail));
        }
    }
}
